steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Run the application
  - name: 'node:14' # Specify the Node.js version you are using
    args: ['node', 'discord.js']

# Specify the Node.js version used for the build environment
images:
  - 'node:14'

