steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/discord-karma', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-karma']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'run.googleapis.com',
           '--image', 'gcr.io/$PROJECT_ID/discord-karma',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/discord-karma'
